### ISSUE TITLE
pod install errors

### ISSUE THREAD

**Issue by lufthansa747** [tidwall/Safe#10]
in my podfile i have 

`use_frameworks!
pod 'Safe', :git => 'https://github.com/tidwall/Safe.git'`

and when i run pod install i get

> Analyzing dependencies
> Pre-downloading: `Safe` from `https://github.com/tidwall/Safe.git`
> [!] Unable to find a specification for 'Safe'.
> 
> [!] Unable to load a podspec from `Safe.podspec`, skipping:
> 
> Pod::DSLError

just using "pod 'Safe'" in the pod file doesn't work either

**Comment by lufthansa747** [comment]
#11

**Comment by tidwall** [comment]
@lufthansa747 Thanks a bunch for fixing this!
