### ISSUE TITLE
Swift3

### ISSUE THREAD

**Issue by nsleche** [tidwall/Safe#12]
It would be nice o have a swift 3 version, if you have interest, create a swift3 branch and I would like to help in the migration.

**Comment by tidwall** [comment]
Sounds good. I just created a branch named `swift/3.0`.

**Comment by tidwall** [comment]
I'm closing this issue for now. Thanks.

**Comment by sunapi386** [comment]
I think the issue should remain open for folks who are also looking to request Swift 3.0 support, until its release.

**Comment by grubino** [comment]
I don't see the swift 3 branch...  has it been removed?

**Comment by tidwall** [comment]
@grubino I think there may be some confusion. It looks like Safe is not currently swift/3 ready. There was a branch a while back but it was empty. I'm closing this issue again. Sorry about the mixup.

**Comment by sunapi386** [comment]
@tidwall so shouldn't we leave the issue open until Swift 3 support is out? Closing it is like saying we don't intend to support Swift 3.

**Comment by grubino** [comment]
Thanks for clearing it up @tidwall  I hope you support Swift 3 soon!  Until then, I won't be able to use Safe :(

**Comment by tidwall** [comment]
I opened a shiny new issue #13.
