### ISSUE TITLE
error using SPM - fix: move the file(s) inside a module

### ISSUE THREAD

**Issue by johndpope** [tidwall/Safe#16]
Fetching https://github.com/tidwall/Safe
Cloning https://github.com/tidwall/Safe
Resolving https://github.com/tidwall/Safe at 1.2.1
error: the package has an unsupported layout, unexpected source file(s) found: /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow/tensorflow/swift/.build/checkouts/Safe-5061242610371348105/Tests/atomic-test.swift, /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow/tensorflow/swift/.build/checkouts/Safe-5061242610371348105/Tests/bridge.m, /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow/tensorflow/swift/.build/checkouts/Safe-5061242610371348105/Tests/chan-test.swift, /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow/tensorflow/swift/.build/checkouts/Safe-5061242610371348105/Tests/dispatch-test.swift, /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow/tensorflow/swift/.build/checkouts/Safe-5061242610371348105/Tests/sync-test.swift, /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow/tensorflow/swift/.build/checkouts/Safe-5061242610371348105/Tests/test.swift
fix: move the file(s) inside a module

I included files - but am getting these errors - perhaps this PR will fix?
https://github.com/tidwall/Safe/pull/15

**Comment by tidwall** [comment]
I just merged #17 updates for Swift 4 support.
